import { NewsArticle, NewsProvider, NewsQuery } from './types';

const MOCK_ARTICLES: Record<string, NewsArticle[]> = {
  '반도체': [
    {
      title: 'AI 데이터센터 투자 급증에 국내 반도체 업황 회복 기대 커져',
      description: '미국 빅테크의 AI 인프라 지출이 올해 역대 최대 규모를 기록할 전망이며, 국내 메모리 반도체 수요가 동반 확대될 것이라는 기대감이 높아지고 있다.',
      link: '',
      publishedAt: '2026-05-14T00:30:00.000Z',
      source: '전자신문',
      matchedKeywords: ['반도체'],
    },
    {
      title: '삼성전자 DS부문 3분기 흑자 전환 전망…메모리 가격 반등 본격화',
      description: '주요 증권사들은 삼성전자 반도체 부문이 3분기 중 실적 반등을 이룰 것으로 내다보며 목표주가를 잇따라 상향 조정했다.',
      link: '',
      publishedAt: '2026-05-14T01:00:00.000Z',
      source: '한국경제',
      matchedKeywords: ['반도체'],
    },
    {
      title: 'SK하이닉스 HBM3E 양산 확대, 엔비디아 공급 비중 증가 확인',
      description: 'SK하이닉스가 엔비디아 차세대 GPU용 HBM3E 공급량을 전분기 대비 40% 이상 늘릴 계획이라고 밝혔다.',
      link: '',
      publishedAt: '2026-05-14T01:50:00.000Z',
      source: '조선비즈',
      matchedKeywords: ['반도체'],
    },
    {
      title: 'TSMC 수주 확대로 국내 반도체 소재·부품 업계도 수혜 기대',
      description: 'TSMC의 선단 공정 가동률이 상승하면서 국내 화학 소재 및 부품 협력사들의 매출 증가로 이어질 것이라는 분석이 나온다.',
      link: '',
      publishedAt: '2026-05-14T02:10:00.000Z',
      source: '디일렉',
      matchedKeywords: ['반도체'],
    },
  ],
  '2차전지': [
    {
      title: '전기차 수요 둔화 장기화에 배터리 업계 재고 부담 확대',
      description: '글로벌 전기차 판매 증가세가 예상보다 더디게 회복되면서 국내 배터리 3사의 재고 조정이 하반기까지 이어질 수 있다는 관측이 나온다.',
      link: '',
      publishedAt: '2026-05-14T01:10:00.000Z',
      source: '머니투데이',
      matchedKeywords: ['2차전지'],
    },
    {
      title: '리튬 가격 반등 조짐…배터리 소재 원가 부담 축소 가능성',
      description: '국제 리튬 현물가격이 연초 대비 12% 반등하며 배터리 소재 업체들의 원가 부담이 일부 완화될 것으로 예상된다.',
      link: '',
      publishedAt: '2026-05-14T02:00:00.000Z',
      source: '이데일리',
      matchedKeywords: ['2차전지'],
    },
    {
      title: 'LG에너지솔루션 북미 공장 가동률 개선세…하반기 본격 회복 전망',
      description: 'LG에너지솔루션이 미국 미시간·오하이오 공장의 가동률을 60%대에서 70%대로 끌어올리며 수익성 개선을 예고했다.',
      link: '',
      publishedAt: '2026-05-14T02:30:00.000Z',
      source: '서울경제',
      matchedKeywords: ['2차전지'],
    },
    {
      title: '에코프로비엠, 차세대 하이니켈 양극재 양산 테스트 완료',
      description: '에코프로비엠이 니켈 함량 94% 이상의 차세대 하이니켈 양극재 양산 테스트를 마치고 주요 셀 업체에 샘플을 공급했다고 밝혔다.',
      link: '',
      publishedAt: '2026-05-14T03:00:00.000Z',
      source: '비즈워치',
      matchedKeywords: ['2차전지'],
    },
  ],
  '바이오': [
    {
      title: 'K-바이오 글로벌 기술수출 올 상반기 2조 돌파…역대 최고 기록',
      description: '국내 바이오·제약 업계의 해외 기술 수출 계약 총액이 올 상반기 기준 2조원을 돌파하며 사상 최대치를 경신했다.',
      link: '',
      publishedAt: '2026-05-14T00:45:00.000Z',
      source: '바이오스펙테이터',
      matchedKeywords: ['바이오'],
    },
    {
      title: '셀트리온 바이오시밀러 유럽 시장 점유율 30% 돌파',
      description: '셀트리온의 항체 바이오시밀러가 유럽 주요 5개국 시장에서 점유율 30%를 넘어서며 오리지널 의약품을 위협하고 있다.',
      link: '',
      publishedAt: '2026-05-14T01:30:00.000Z',
      source: '청년의사',
      matchedKeywords: ['바이오'],
    },
    {
      title: '한미약품 GLP-1 계열 비만 치료제 국내 임상 2상 진입',
      description: '한미약품이 자체 개발한 주 1회 투여 GLP-1 계열 비만 치료제가 식약처로부터 임상 2상 승인을 받았다.',
      link: '',
      publishedAt: '2026-05-14T02:20:00.000Z',
      source: '약업신문',
      matchedKeywords: ['바이오'],
    },
    {
      title: '식약처, 첨단재생의료제품 심사 기간 기존의 절반으로 단축 추진',
      description: '식품의약품안전처가 첨단재생의료제품의 신속 심사 절차를 확대해 시장 출시까지 걸리는 기간을 기존 2년에서 1년 이내로 줄이겠다는 계획을 발표했다.',
      link: '',
      publishedAt: '2026-05-14T03:15:00.000Z',
      source: '메디파나뉴스',
      matchedKeywords: ['바이오'],
    },
  ],
  'AI': [
    {
      title: '네이버 하이퍼클로바X 기업용 서비스 고객사 2000개 돌파',
      description: '네이버의 한국어 특화 LLM 하이퍼클로바X를 기반으로 한 B2B 솔루션 구독 기업이 2000개를 넘어섰다고 네이버가 밝혔다.',
      link: '',
      publishedAt: '2026-05-14T01:00:00.000Z',
      source: '지디넷코리아',
      matchedKeywords: ['AI'],
    },
    {
      title: '국내 AI 스타트업 투자 규모 1조 돌파 전망…작년 대비 2배',
      description: '올해 국내 AI 스타트업에 유입된 투자 금액이 연내 1조원을 넘길 것으로 예상되며, 이는 지난해 같은 기간 대비 두 배 이상 증가한 수치다.',
      link: '',
      publishedAt: '2026-05-14T01:40:00.000Z',
      source: '벤처스퀘어',
      matchedKeywords: ['AI'],
    },
    {
      title: '삼성전자, 온디바이스 AI 전용 NPU 칩 개발 완료…하반기 양산',
      description: '삼성전자가 스마트폰에 직접 탑재 가능한 온디바이스 AI 추론 칩 개발을 마무리하고, 갤럭시 차기 플래그십 모델에 적용할 계획이다.',
      link: '',
      publishedAt: '2026-05-14T02:15:00.000Z',
      source: '전자신문',
      matchedKeywords: ['AI'],
    },
    {
      title: 'KT, AI 데이터센터 추가 구축 발표…2027년까지 5000억 투자',
      description: 'KT가 경기 수원과 부산에 AI 전용 데이터센터를 추가로 구축하고 2027년까지 총 5000억원을 투입한다는 계획을 공식 발표했다.',
      link: '',
      publishedAt: '2026-05-14T02:50:00.000Z',
      source: '아이뉴스24',
      matchedKeywords: ['AI'],
    },
  ],
  '로봇': [
    {
      title: '현대차 보스턴다이내믹스, 국내 대형 물류센터 산업용 로봇 대규모 수주',
      description: '현대자동차 계열사 보스턴다이내믹스가 국내 대형 이커머스 물류센터 3곳에 스트레치 로봇 수백 대를 공급하는 계약을 체결했다.',
      link: '',
      publishedAt: '2026-05-14T00:50:00.000Z',
      source: '로봇신문',
      matchedKeywords: ['로봇'],
    },
    {
      title: '국내 협동로봇 시장 연 30% 성장…중소 제조업 자동화 수요 견인',
      description: '한국로봇산업진흥원에 따르면 국내 협동로봇 시장이 3년 연속 30% 이상 성장하고 있으며, 중소 제조업체의 공정 자동화 도입이 주된 요인으로 꼽혔다.',
      link: '',
      publishedAt: '2026-05-14T01:20:00.000Z',
      source: '중소기업신문',
      matchedKeywords: ['로봇'],
    },
    {
      title: '레인보우로보틱스 삼성전자와 협력 확대…반도체 제조용 로봇 개발',
      description: '레인보우로보틱스가 삼성전자와 공동으로 반도체 웨이퍼 이송 전용 협동로봇을 개발 중이며, 연내 파일럿 테스트를 진행할 예정이다.',
      link: '',
      publishedAt: '2026-05-14T02:05:00.000Z',
      source: '테크크런치코리아',
      matchedKeywords: ['로봇'],
    },
    {
      title: '정부, 로봇 산업 육성에 3년간 1조원 투자 계획 확정',
      description: '산업통상자원부가 첨단로봇 핵심 부품 국산화와 서비스 로봇 시범 보급 사업을 포함한 3개년 로봇 산업 육성 계획을 확정했다.',
      link: '',
      publishedAt: '2026-05-14T03:00:00.000Z',
      source: '연합뉴스',
      matchedKeywords: ['로봇'],
    },
  ],
  '국내 증시': [
    {
      title: '코스피, 외국인 순매수에 2700선 회복…반도체·자동차 동반 상승',
      description: '외국인 투자자들이 반도체와 자동차 대형주를 집중 매수하며 코스피가 2700선을 회복했다. 시장에서는 미국 금리 인하 기대감이 반영됐다는 분석이 나온다.',
      link: '',
      publishedAt: '2026-05-14T00:10:00.000Z',
      source: '연합인포맥스',
      matchedKeywords: ['국내 증시'],
    },
    {
      title: '코스닥 700선 돌파 시도…바이오·2차전지 중소형주 강세',
      description: '코스닥 지수가 700선 회복을 시도하는 가운데 바이오와 2차전지 관련 중소형주들이 장 초반부터 강세를 보이고 있다.',
      link: '',
      publishedAt: '2026-05-14T00:25:00.000Z',
      source: '파이낸셜뉴스',
      matchedKeywords: ['국내 증시'],
    },
    {
      title: '오늘 증시 전망: 미 증시 강세 마감에 국내도 상승 출발 예상',
      description: '전날 미국 나스닥이 1.2% 상승 마감하면서 국내 증시도 기술주 중심으로 강세 출발이 예상된다. 환율 안정도 긍정적 요인으로 꼽힌다.',
      link: '',
      publishedAt: '2026-05-14T00:05:00.000Z',
      source: '한국경제',
      matchedKeywords: ['국내 증시'],
    },
    {
      title: '5월 외국인 누적 순매수 1조 돌파…IT·헬스케어 주도',
      description: '5월 들어 외국인 투자자들이 국내 증시에서 IT와 헬스케어 섹터를 중심으로 1조원 이상을 순매수한 것으로 집계됐다.',
      link: '',
      publishedAt: '2026-05-14T01:00:00.000Z',
      source: '이데일리',
      matchedKeywords: ['국내 증시'],
    },
  ],
  'AI 데이터센터': [
    {
      title: '전력망 부족이 AI 데이터센터 확장 최대 걸림돌…국내도 예외 없어',
      description: '급격한 AI 데이터센터 수요 증가로 전력 공급 인프라가 병목 구간이 되고 있으며, 국내 통신사와 IT 기업들도 전력 확보에 비상이 걸린 상황이다.',
      link: '',
      publishedAt: '2026-05-14T00:35:00.000Z',
      source: '전자신문',
      matchedKeywords: ['AI 데이터센터'],
    },
    {
      title: 'SKT·KT·LGU+ 삼사, AI 데이터센터 설비투자 경쟁 본격화',
      description: '국내 통신 3사가 앞다퉈 AI 데이터센터 구축에 대규모 자본을 투입하면서 서버·냉각 장비·전력설비 관련 협력업체들의 수주 경쟁도 치열해지고 있다.',
      link: '',
      publishedAt: '2026-05-14T01:05:00.000Z',
      source: '디지털타임스',
      matchedKeywords: ['AI 데이터센터'],
    },
    {
      title: '엔비디아 GB200 공급망 확보 경쟁…국내 PCB·전원 모듈 업체 주목',
      description: '엔비디아의 차세대 GPU 플랫폼 GB200 관련 부품 공급망에 편입된 국내 PCB 및 전원 모듈 업체들이 수혜주로 부각되고 있다.',
      link: '',
      publishedAt: '2026-05-14T01:55:00.000Z',
      source: '매일경제',
      matchedKeywords: ['AI 데이터센터'],
    },
    {
      title: '정부, AI 데이터센터 특화 산업단지 지정 추진…세제 혜택도 검토',
      description: '과학기술정보통신부가 AI 데이터센터 전용 산업단지를 신규 지정해 입주 기업에 세제·규제 혜택을 부여하는 방안을 추진 중이라고 밝혔다.',
      link: '',
      publishedAt: '2026-05-14T02:40:00.000Z',
      source: '아이뉴스24',
      matchedKeywords: ['AI 데이터센터'],
    },
  ],
  '자동차': [
    {
      title: '현대차그룹 4월 글로벌 판매 전년비 5% 증가…북미 SUV 호조',
      description: '현대자동차그룹이 4월 전 세계에서 약 67만 대를 판매해 전년 같은 달보다 5% 증가했으며, 북미 시장에서의 SUV 수요 강세가 실적을 이끌었다.',
      link: '',
      publishedAt: '2026-05-14T00:40:00.000Z',
      source: '오토타임즈',
      matchedKeywords: ['자동차'],
    },
    {
      title: '전기차 보조금 추가 축소에 내연기관차 수요 반사이익 지속',
      description: '정부의 전기차 보조금이 추가 감소하면서 소비자들이 내연기관 차량으로 선택을 돌리는 경향이 강해지고 있다는 분석이 나왔다.',
      link: '',
      publishedAt: '2026-05-14T01:15:00.000Z',
      source: '카미디어',
      matchedKeywords: ['자동차'],
    },
    {
      title: '기아 EV9 북미 판매 호조…4월 누적 1만 대 돌파',
      description: '기아의 대형 전기 SUV EV9가 북미 시장에서 4월 누적 판매 1만 대를 돌파하며 프리미엄 전기차 시장에서 자리를 잡아가고 있다.',
      link: '',
      publishedAt: '2026-05-14T02:00:00.000Z',
      source: '뉴스1',
      matchedKeywords: ['자동차'],
    },
    {
      title: '자율주행 레벨3 상용화 일정 지연…완성차 업계 로드맵 재정비',
      description: '법규·인프라 준비 부족으로 자율주행 레벨3 상용화 일정이 1~2년 지연될 것으로 예상되며, 주요 완성차 업체들이 로드맵을 조정하고 있다.',
      link: '',
      publishedAt: '2026-05-14T02:45:00.000Z',
      source: '오토데일리',
      matchedKeywords: ['자동차'],
    },
  ],
};

const ALL_MOCK_ARTICLES: NewsArticle[] = Object.values(MOCK_ARTICLES).flat();

export const mockNewsProvider: NewsProvider = {
  async fetchNews({ keyword, display = 10 }: NewsQuery): Promise<NewsArticle[]> {
    const articles = MOCK_ARTICLES[keyword] ?? ALL_MOCK_ARTICLES;
    return articles.slice(0, display);
  },
};
