/** Machine-readable collect / fallback reason codes */
export type CommunityCollectCode =
  | 'OK'
  | 'NAVER_DISCUSS_FETCH_FAILED'
  | 'NAVER_DISCUSS_HTTP_ERROR'
  | 'NAVER_DISCUSS_JSON_PARSE_ERROR'
  | 'NAVER_DISCUSS_API_REJECTED'
  | 'NAVER_DISCUSS_EMPTY_RESPONSE'
  | 'NAVER_DISCUSS_FILTERED_EMPTY'
  | 'SEARCH_API_SKIPPED'
  | 'SEARCH_API_FETCH_FAILED'
  | 'SEARCH_API_401'
  | 'SEARCH_API_403'
  | 'SEARCH_API_HTTP_ERROR'
  | 'SEARCH_API_429'
  | 'SEARCH_API_JSON_PARSE_ERROR'
  | 'SEARCH_API_EMPTY_RESPONSE'
  | 'SOURCE_COOLDOWN_SKIP'
  | 'SOURCE_UNAVAILABLE'
  | 'MARKET_DATA_LIVE_OK'
  | 'MARKET_DATA_FETCH_FAILED'
  | 'MARKET_DATA_FALLBACK_MOCK'
  | 'TICKER_NO_POSTS'
  | 'LIVE_COLLECT_NO_ITEMS'
  | 'FALLBACK_MOCK_COLLECT'
  | 'LIVE_COLLECT_EXCEPTION';

export const COLLECT_CODE_LABEL: Record<CommunityCollectCode, string> = {
  OK: '정상',
  NAVER_DISCUSS_FETCH_FAILED: '종토방 네트워크 실패',
  NAVER_DISCUSS_HTTP_ERROR: '종토방 HTTP 오류',
  NAVER_DISCUSS_JSON_PARSE_ERROR: '종토방 JSON 파싱 실패',
  NAVER_DISCUSS_API_REJECTED: '종토방 API 거부',
  NAVER_DISCUSS_EMPTY_RESPONSE: '종토방 빈 응답',
  NAVER_DISCUSS_FILTERED_EMPTY: '종토방 24h 필터 후 0건',
  SEARCH_API_SKIPPED: '검색 API 키 없음 (스킵)',
  SEARCH_API_FETCH_FAILED: '검색 API 네트워크 실패',
  SEARCH_API_401: '검색 API 401 (인증 실패)',
  SEARCH_API_403: '검색 API 403',
  SEARCH_API_HTTP_ERROR: '검색 API HTTP 오류',
  SEARCH_API_429: '검색 API 429 (rate limit)',
  SEARCH_API_JSON_PARSE_ERROR: '검색 JSON 파싱 실패',
  SEARCH_API_EMPTY_RESPONSE: '검색 결과 0건',
  SOURCE_COOLDOWN_SKIP: '검색 쿨다운 · 캐시 사용',
  SOURCE_UNAVAILABLE: '검색 source unavailable',
  MARKET_DATA_LIVE_OK: '시세 실시간',
  MARKET_DATA_FETCH_FAILED: '시세 조회 실패',
  MARKET_DATA_FALLBACK_MOCK: '시세 mock fallback',
  TICKER_NO_POSTS: '종목 게시물 없음',
  LIVE_COLLECT_NO_ITEMS: '라이브 수집 0종목',
  FALLBACK_MOCK_COLLECT: 'mock fallback',
  LIVE_COLLECT_EXCEPTION: '라이브 수집 예외',
};
